<a href="https://colab.research.google.com/github/rajeev-gautam/Final_AI_Portfolio_Preparation/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Computing Toolkit with NumPy**

## Importing Important Libraries

In [ ]:
import numpy as np
import time

## Vector Operations Using Loops

In [ ]:
def vec_add(a, b):
    res = []
    for i in range(len(a)):
        res.append(a[i] + b[i])
    return res

def vec_sub(a, b):
    res = []
    for i in range(len(a)):
        res.append(a[i] - b[i])
    return res

def vec_elem_mul(a, b):
    res = []
    for i in range(len(a)):
        res.append(a[i] * b[i])
    return res

def vec_dot(a, b):
    total = 0
    for i in range(len(a)):
        total += a[i] * b[i]
    return total

def vec_normalize(a):
    total = 0
    for x in a:
        total += x * x
    mag = total ** 0.5

    res = []
    for x in a:
        res.append(x / mag)
    return res

In [ ]:
v1 = [1, 2, 3, 4, 5]
v2 = [6, 7, 8, 9, 10]

vec_add(v1, v2), vec_sub(v1, v2), vec_elem_mul(v1, v2), vec_dot(v1, v2), vec_normalize(v1)

([7, 9, 11, 13, 15],
 [-5, -5, -5, -5, -5],
 [6, 14, 24, 36, 50],
 130,
 [0.13483997249264842,
  0.26967994498529685,
  0.40451991747794525,
  0.5393598899705937,
  0.674199862463242])

## Vector Operations using Numpy

In [ ]:
def vec_add_np(a, b): return a + b
def vec_sub_np(a, b): return a - b
def vec_elem_mul_np(a, b): return a * b
def vec_dot_np(a, b): return np.dot(a, b)
def vec_normalize_np(a): return a / np.linalg.norm(a)

In [ ]:
v1_np = np.array(v1)
v2_np = np.array(v2)

vec_add_np(v1_np, v2_np), vec_sub_np(v1_np, v2_np), vec_elem_mul_np(v1_np, v2_np), vec_dot_np(v1_np, v2_np), vec_normalize_np(v1_np)

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 np.int64(130),
 array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986]))

## Matrix Operations using Loops

In [ ]:
def mat_add(A, B):
    res = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] + B[i][j])
        res.append(row)
    return res

def mat_sub(A, B):
    res = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] - B[i][j])
        res.append(row)
    return res

def mat_multiply(A, B):
    res = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            total = 0
            for k in range(len(B)):
                total += A[i][k] * B[k][j]
            row.append(total)
        res.append(row)
    return res

def mat_transpose(A):
    res = []
    for j in range(len(A[0])):
        row = []
        for i in range(len(A)):
            row.append(A[i][j])
        res.append(row)
    return res

In [ ]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

mat_add(A, B), mat_sub(A, B), mat_multiply(A, B), mat_transpose(A)

([[6, 8], [10, 12]],
 [[-4, -4], [-4, -4]],
 [[19, 22], [43, 50]],
 [[1, 3], [2, 4]])

## Matrix Operations using Numpy

In [ ]:
def mat_add_np(A, B): return A + B
def mat_sub_np(A, B): return A - B
def mat_multiply_np(A, B): return A @ B
def mat_transpose_np(A): return A.T

In [ ]:
A_np = np.array(A)
B_np = np.array(B)

mat_add_np(A_np, B_np), mat_sub_np(A_np, B_np), mat_multiply_np(A_np, B_np), mat_transpose_np(A_np)

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[19, 22],
        [43, 50]]),
 array([[1, 3],
        [2, 4]]))

## Comparing Python Loops VS Numpy Performance (Vector Operations)

In [ ]:
size = 300_000
a = list(range(size))
b = list(range(size))

a_np = np.array(a)
b_np = np.array(b)

def time_it(func, *args):
    start = time.time()
    func(*args)
    return time.time() - start

print("VECTOR PERFORMANCE\n")

print("Add:", time_it(vec_add, a, b), "|", time_it(vec_add_np, a_np, b_np))
print("Sub:", time_it(vec_sub, a, b), "|", time_it(vec_sub_np, a_np, b_np))
print("Elem Mul:", time_it(vec_elem_mul, a, b), "|", time_it(vec_elem_mul_np, a_np, b_np))
print("Dot:", time_it(vec_dot, a, b), "|", time_it(vec_dot_np, a_np, b_np))
print("Normalize:", time_it(vec_normalize, a), "|", time_it(vec_normalize_np, a_np))

VECTOR PERFORMANCE

Add: 0.0332486629486084 | 0.0010228157043457031
Sub: 0.018527984619140625 | 0.0005714893341064453
Elem Mul: 0.026894330978393555 | 0.0006113052368164062
Dot: 0.028925657272338867 | 0.0005218982696533203
Normalize: 0.043207645416259766 | 0.0014772415161132812


## Comparing Python Loops VS Numpy Performance (Matrix Operations)

In [ ]:
n = 400
A = [[i for i in range(n)] for _ in range(n)]
B = [[i for i in range(n)] for _ in range(n)]

A_np = np.array(A)
B_np = np.array(B)

print("\nMATRIX PERFORMANCE\n")

print("Add:", time_it(mat_add, A, B), "|", time_it(mat_add_np, A_np, B_np))
print("Sub:", time_it(mat_sub, A, B), "|", time_it(mat_sub_np, A_np, B_np))
print("Multiply:", time_it(mat_multiply, A, B), "|", time_it(mat_multiply_np, A_np, B_np))
print("Transpose:", time_it(mat_transpose, A), "|", time_it(mat_transpose_np, A_np))


MATRIX PERFORMANCE

Add: 0.02348160743713379 | 0.00034999847412109375
Sub: 0.01141357421875 | 0.0002949237823486328
Multiply: 7.918534278869629 | 0.08941340446472168
Transpose: 0.013030290603637695 | 7.62939453125e-06
